ivy:
  download-url: http://search.maven.org/remotecontent?filepath=org/apache/ivy/ivy/${ivy-version}/ivy-${ivy-version}.jar
  jar: plugins/${project.artifactId}/ivy-${ivy-version}.jar
  cache: plugins/${project.artifactId}/ivy